version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: genially
      MONGO_INITDB_ROOT_PASSWORD: genially
      MONGO_INITDB_DATABASE: backend_test
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  genially:
    build: .
    environment:
      MONGO_HOST: mongodb://genially:genially@mongodb:27017
    ports:
      - 3000:3000
    depends_on:
      mongodb:
        condition: service_healthy